# SPDX-License-Identifier: GPL-2.0-only
dtb-$(CONFIG_ARCH_STM32) += \
	stm32mp215f-dk.dtb \
	stm32mp235f-dk.dtb \
	stm32mp257f-dk.dtb \
	stm32mp257f-ev1.dtb \
	stm32mp257d-atk-ddr-1GB.dtb	\
	stm32mp257d-atk-ddr-1GB-rgb.dtb \
	stm32mp257d-atk-ddr-1GB-mipi.dtb \
	stm32mp257d-atk-ddr-1GB-lvds-1xSingleLink.dtb \
	stm32mp257d-atk-ddr-1GB-lvds-2xSingleLink.dtb \
	stm32mp257d-atk-ddr-1GB-lvds-dualLink.dtb \
	stm32mp257d-atk-ddr-2GB.dtb	\
	stm32mp257d-atk-ddr-2GB-rgb.dtb \
	stm32mp257d-atk-ddr-2GB-mipi.dtb \
	stm32mp257d-atk-ddr-2GB-lvds-1xSingleLink.dtb \
	stm32mp257d-atk-ddr-2GB-lvds-2xSingleLink.dtb \
	stm32mp257d-atk-ddr-2GB-lvds-dualLink.dtb